### ISSUE TITLE
Onsen 2 javascript documentation is empty

### ISSUE THREAD

**Issue by IliaSky** [OnsenUI/onsen.io#111]
https://onsen.io/2/reference/javascript.html
![screen shot 2016-02-12 at 8 42 22 pm](https://cloud.githubusercontent.com/assets/2514449/13006000/4d49f492-d1c9-11e5-94dd-17b261986d6b.png)

**Comment by anatoo** [comment]
Probably we should merge this changes: https://github.com/OnsenUI/onsen.io/pull/106.

**Comment by argelius** [comment]
Sorry! I forgot to merge that PR :(
