### ISSUE TITLE
ons.notification layout is broken in Android 

### ISSUE THREAD

**Issue by kanakoubukata** [OnsenUI/onsen.io#253]
see attached file.

![ons-notification](https://cloud.githubusercontent.com/assets/8393422/18662550/cb44c16c-7f55-11e6-86be-53b5a56498cc.png)

**Comment by kanakoubukata** [comment]
I mistook onsen.io for Onsen UI.

**Comment by frankdiox** [comment]
@kanakoubukata This is a real issue that happens in the current master branch.
