### ISSUE TITLE
Angular 2+ css import error

### ISSUE THREAD

**Issue by danielszuk** [OnsenUI/onsen.io#494]
I have an Angular 2+ project with scss styleengine (created by angular cli _ng new app --style=scss_), the angular cli install itself with the following dependencies:
**css-loader@0.28.10
postcss-loader@2.1.1
sass-loader@6.0.6**

With this configuration if I follow the documentation and try to import the onsenui css files with
_@import '../node_modules/onsenui/css/onsenui.css';
@import '../node_modules/onsenui/css/onsen-css-components.css';_

In buildtime I got error:
**ERROR in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles.scss
Module build failed: Error: Can't resolve 'ionicons/css/ionicons.min.css' in 'your-project-path\node_modules\onsenui\css'**

I have to open the node_modules\onsenui\css\onsenui.css file and manually change the imports path to relative paths (e.x. from ionicons/css/ionicons.min.css to ./ionicons/css/ionicons.min.css):
_@import url("./ionicons/css/ionicons.min.css");
@import url("./material-design-iconic-font/css/material-design-iconic-font.min.css");
@import url("./font_awesome/css/font-awesome.min.css");_

**Comment by asialgearoid** [comment]
Hi @danielszuk, this repository is specifically for the onsen.io website. If you have an issue with the Onsen UI library, please post your issue on the library's issue tracker: https://github.com/OnsenUI/OnsenUI/issues
