### ISSUE TITLE
react bindings as dev dependency?

### ISSUE THREAD

**Issue by avalanche1** [OnsenUI/onsen.io#503]
Why does https://onsen.io/v2/guide/react/ says to install react bindings as dev dependency?
`$ npm install onsenui react-onsenui --save-dev`

Is it a mistake?

**Comment by asialgearoid** [comment]
You are right, this should just be `--save`. Thanks for pointing it out. I've fixed it and it will be reflected on the website shortly.

**Comment by avalanche1** [comment]
Actually this sd be sufficient
`$ npm i onsenui react-onsenui`
