### ISSUE TITLE
add links to components page

### ISSUE THREAD

**Issue by avalanche1** [OnsenUI/onsen.io#505]
I would like https://onsen.io/theme-roller/ to have links to implementation.
I like some of the examples but I don't know how to achieve the same design with current onsen docs. I'd really love to see the markup.

**Comment by asialgearoid** [comment]
@avalanche1 The components shown in the theme roller are written using Vue. It would be quite time-consuming to show the implementation for all bindings, which is why we don't show the code. If you are interested in seeing it, all the code for that page is at https://github.com/OnsenUI/theme-roller
